version: '3'
name: zambranodockerizado-ecomers
services:
  ca-courses-service:
    container_name: UsersService
    build: ./
    image: zambranodockerizado/ecomers:UsersService
    ports:
      - "8002:8002"
    depends_on:
      ca-database-postgres:
        condition: service_healthy
      ca-keycloack:
        condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://ca-database-mysql:3306/appdb
      - spring.datasource.username=root
      - spring.datasource.password=12345678
      - KEYCLOAK_ISSUER_URI=http://ca-keycloack:8080/realms/CoursesApp
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://ca-keycloack:8080/realms/CoursesApp
  ca-database-mysql:
    container_name: ca-database-mysql
    image: "mysql:latest"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdb
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      interval: 1s
      retries: 10
  ca-keycloack:
    container_name: ca-keycloack
    image: "quay.io/keycloak/keycloak:latest"
    command: start-dev
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_PORT=8080
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL=jdbc:mysql://ca-database-myql:3306/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    restart: always
    depends_on:
      ca-database-postgres-keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 3s
      timeout: 5s
      retries: 10