version: '3.8'

services:
  web:
    build:
      context: ./Service
    ports:
      - "5000:5000"
    volumes:
      - ./Service/uploads:/app/uploads
    depends_on:
      - db

  db:
    container_name: imageAnalyzer_db
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: imageAnalyzer
    volumes:
      - ./data:/var/lib/postgresql/data
