server:
  port: 8084

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/SpringBootKeycloak

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  feign:
    user-service:
      url: http://localhost:8081